### PR TITLE
Provide an option to acess web-term outside of localhost

### PR DESCRIPTION
**Pull request by hmalphettes**
Thanks for this project!
I was not able to access the web-interface outside of localhost without this change.
Let me know if I missed something.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@hmalphettes This is great! :sparkles: Can you [also add an example](https://github.com/IonicaBizau/web-term/blob/ee5329ecc1c4276bd9b1a1537bf40104f9b04051/bin/web-term#L35) how to use this?

**Comment by hmalphettes** [comment]
Thanks @IonicaBizau.  Sure, I am using it to access csysdig remotely running in a container:
https://quay.io/repository/sutoiku/sysdig-web-term

So I am adding the example to the code. Note that with this suggested patch web-term is by default listening on "0.0.0.0". It is consistent with node's default behavior but different from the current behavior.

csysdig-remote-access

**Comment by IonicaBizau** [comment]
Thanks a lot! :sparkles:

**Comment by IonicaBizau** [comment]
@hmalphettes Improved in #31. :ship: `4.5.0` :tada:

**Comment by hmalphettes** [comment]
Many thanks @IonicaBizau. Many thanks for improving it so much and releasing it already.

**Comment by IonicaBizau** [comment]
@hmalphettes You're welcome! :+1: Thanks for contributing too! :smile:

**Pull request merged**
