### PR TITLE
Correcting terminal height problem

### LINKED ISSUE #25: Prompt goes past bottom of screen
Hello,

I'm not certain if this is a bug or a user error, but I couldn't find an issue like this.

When using recent versions of chrome the bottom lines of the terminal will always be slightly below the bottom of the window.

To reproduce: Start web-term then hit return until the prompt goes off the bottom of the screen in Chrome 46.

Thank you for your time.

### PR DESCRIPTION
**Pull request by lcristianiim**
Fixes #25 
This should fix the terminal height with the prompt going off the bottom of the page.
@IonicaBizau please check it out.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Hmm, really? :smile:

**Comment by lcristianiim** [comment]
Yeah. It just works.

**Comment by IonicaBizau** [comment]
Hmm, with the Monaco font?

Here is what I got:

image

**Comment by lcristianiim** [comment]
hmm.. thats strange
image
image

**Comment by IonicaBizau** [comment]
From debugging, I saw that the char height is `11` while the row height is `12`. That's the reason. By just adding `+ 1`

Changing [this](https://github.com/IonicaBizau/web-term/blob/0dd3aa628af78beb17d02056d89535204a4dac79/bin/public/js/web-term.js#L43) into something like `y: Math.floor(targetSize.height / (charSize.height + 1))` solves the problem for me, Monaco font, but it fails it for the `monospace` font. :sob:

**Comment by lcristianiim** [comment]
Now it should also work in Chrome.

**Pull request merged**
